const INITIAL_MANA_PER_TURN = 1,
    INITIAL_BASE_STRENGTH = 15,
    NUMBER_OF_ROWS = 6,
    LAST_ROW_INDEX = NUMBER_OF_ROWS - 1,
    ENEMY_TURN_DURATION = 1200; // ms

export {
    ENEMY_TURN_DURATION,
    INITIAL_BASE_STRENGTH,
    INITIAL_MANA_PER_TURN,
    LAST_ROW_INDEX,
    NUMBER_OF_ROWS
};
